services:
   app:
      build:
         context: .
         dockerfile: Dockerfile
      
      container_name: my-portfolio-app
      
      ports:
         - "8080:3000"
      
      # Corrected path to point to the .env file in the config folder
      env_file:
         - ./config/.env.production
   
      restart: always
   
      volumes:
         - .:/usr/src/app
         - /usr/src/app/node_modules