import { AuthService } from "@src/domain/auth/auth.service";
import { IAuthService } from "@src/domain/auth/auth.types";
import { BioRepo } from "@src/domain/Bio/Repository/bio.repo";
import { BioService } from "@src/domain/Bio/Service/bio.service";
import { IBioRepo, IBioService } from "@src/domain/Bio/Types/bio.types";
import { UploadService } from "@src/uploads/image/image.service";
import { IUploadService } from "@src/uploads/image/image.types";
import { SkillRepo } from "@src/domain/Skill/Repository/skill.repo";
import { SkillService } from "@src/domain/Skill/Service/skill.service";
import { ISkillRepo, ISkillService } from "@src/domain/Skill/Types/skill.types";
import { container } from "tsyringe";
import { ProjectRepo } from "@src/domain/Project/Repository/project.repo";
import { ProjectService } from "@src/domain/Project/Service/project.service";

container.register<IBioRepo>("IBioRepo", { useClass: BioRepo });
container.register<IBioService>("IBioService", { useClass: BioService });
container.register<IUploadService>("IUploadService", { useClass: UploadService });
container.register<IAuthService>("IAuthService", { useClass: AuthService });
container.register<ISkillRepo>("ISkillRepo", { useClass: SkillRepo });
container.register<ISkillService>("ISkillService", { useClass: SkillService });
container.register("ProjectRepo", { useClass: ProjectRepo });
container.register("ProjectService", { useClass: ProjectService });
